// Defines the possible views in the application.
export type View = 'builder' | 'about' | 'roadmap';

// Represents a single message in the AI assistant's chat history.
export interface ChatMessage {
  role: 'user' | 'assistant';
  text: string;
}

// Represents a single choice generated by the AI for a course step.
export interface CourseOption {
  title: string;
  details: string;
  isCustom?: boolean; // Flag for user-provided options
}

// Defines the specific steps in the generation process.
export type GenerationStep = 'analysis' | 'objectives' | 'outline' | 'activities';


// Defines the loading states for various asynchronous operations.
export interface LoadingStates {
  analysis: boolean;
  objectives: boolean;
  outline: boolean;
  activities: boolean;
  agent: boolean;
}

// Defines props for the Sidebar component.
export interface SidebarProps {
    isChatExpanded: boolean;
    setIsChatExpanded: (expanded: boolean) => void;
}

// Defines the shape of the BuilderContext for state management.
export interface BuilderContextType {
  // State for course topic
  courseTopic: string;
  setCourseTopic: (topic: string) => void;

  // State for each step's generated options and selected choice(s)
  analysisOptions: CourseOption[];
  selectedAnalysis: CourseOption | null;
  objectivesOptions: CourseOption[];
  selectedObjectives: CourseOption[]; // Can select multiple
  outlineOptions: CourseOption[];
  selectedOutline: CourseOption | null;
  activitiesOptions: CourseOption[];
  selectedActivities: CourseOption[]; // Can select multiple
  
  // Loading states for UI feedback
  loadingStates: LoadingStates;

  // AI assistant chat history and interaction methods
  chatHistory: ChatMessage[];
  sendChatMessage: (message: string) => void;
  
  // Sidebar visibility state and toggle function
  isSidebarOpen: boolean;
  toggleSidebar: () => void;

  // Functions to trigger AI generation and handle selection for each step
  generateStepContent: (step: GenerationStep) => void;
  selectOption: (step: GenerationStep, option: CourseOption) => void;
  
  // Function to reset the entire builder state
  resetBuilder: () => void;
}